name: FractionCore
version: '${version}'
description: '${description}'
main: pl.Ljimmex.fractionCore.FractionCore
api-version: '1.20'
load: STARTUP
authors: [Ljimex]
website: https://github.com/Ljinmex/FractionCore

permissions:
  fractioncore.admin:
    description: Allows access to admin commands
    default: op
  fractioncore.admin.module:
    description: Allows management of modules
    default: op
  fractioncore.admin.lang.reload:
    description: Allows reloading language files
    default: op
  fractioncore.admin.reload:
    description: Allows reloading configuration files
    default: op
  fractioncore.admin.debug:
    description: Allows toggling debug mode
    default: op

commands:
  guild:
    description: Main FractionCore command
    usage: /guild [args]
    permission: fractioncore.command.guild
    permission-message: You do not have permission to use this command.
